# Generated by Django 4.1 on 2023-04-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_assistence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('hora_ingreso_mañana', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('hora_salida_mañana', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('hora_ingreso_tarde', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('hora_salida_tarde', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
