# Generated by Django 4.1 on 2023-04-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_register_assistence_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_assistence',
            name='constancy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register_assistence',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
