# Generated by Django 4.1 on 2023-04-01 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_register_assistence_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation_rescheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada1', models.DateTimeField(blank=True, null=True)),
                ('fecha_programada2', models.DateTimeField(blank=True, null=True)),
                ('fecha_de_reprogramación1', models.DateTimeField(blank=True, null=True)),
                ('fecha_de_reprogramación2', models.DateTimeField(blank=True, null=True)),
                ('fecha_de_reprogramación3', models.DateTimeField(blank=True, null=True)),
                ('motivos_de_reprogramación', models.CharField(blank=True, max_length=200, null=True)),
                ('justificación_de_la_reprogramación', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
