# Generated by Django 4.1 on 2023-04-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_vacation_rescheduling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation_rescheduling',
            old_name='fecha_de_reprogramación1',
            new_name='fecha_de_reprogramación1_desde',
        ),
        migrations.RenameField(
            model_name='vacation_rescheduling',
            old_name='fecha_de_reprogramación2',
            new_name='fecha_de_reprogramación1_hasta',
        ),
        migrations.RenameField(
            model_name='vacation_rescheduling',
            old_name='fecha_de_reprogramación3',
            new_name='fecha_de_reprogramación2_desde',
        ),
        migrations.RenameField(
            model_name='vacation_rescheduling',
            old_name='fecha_programada1',
            new_name='fecha_de_reprogramación2_hasta',
        ),
        migrations.RenameField(
            model_name='vacation_rescheduling',
            old_name='fecha_programada2',
            new_name='fecha_de_reprogramación3_desde',
        ),
        migrations.AddField(
            model_name='vacation_rescheduling',
            name='fecha_de_reprogramación3_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacation_rescheduling',
            name='fecha_programada1_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacation_rescheduling',
            name='fecha_programada1_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacation_rescheduling',
            name='fecha_programada2_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacation_rescheduling',
            name='fecha_programada2_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
