# Generated by Django 4.1 on 2023-04-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_fecha_de_reprogramación1_vacation_rescheduling_fecha_de_reprogramación1_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation_rescheduling',
            name='dias_habiles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
