# Generated by Django 4.1 on 2023-04-01 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_vacation_rescheduling_dias_habiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Official_permit_for_hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisión', models.CharField(blank=True, max_length=200, null=True)),
                ('motivo_de_la_comisión', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_de_salida', models.DateTimeField(blank=True, null=True)),
                ('desde_hora', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('hasta_hora', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
