# Generated by Django 4.1 on 2023-04-01 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0013_official_permit_for_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_leave_with_pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensación', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_de_compensación', models.DateTimeField(blank=True, null=True)),
                ('compensación_desde_hora', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('compensación_hasta_hora', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('fecha_de_salida', models.DateTimeField(blank=True, null=True)),
                ('salida_desde_hora', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('salida_hasta_hora', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
