# Generated by Django 4.1 on 2023-04-01 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0014_personal_leave_with_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation_account_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_solicitud', models.DateTimeField(blank=True, null=True)),
                ('fecha_solicitada1', models.DateTimeField(blank=True, null=True)),
                ('fecha_solicitada2', models.DateTimeField(blank=True, null=True)),
                ('fecha_solicitada3', models.DateTimeField(blank=True, null=True)),
                ('dias_habiles', models.IntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=500, null=True)),
                ('justificación', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
