# Generated by Django 4.1 on 2023-04-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_data_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_RRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('a_paterno', models.CharField(blank=True, max_length=15, null=True)),
                ('a_materno', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=25)),
                ('item', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
