# Generated by Django 4.1 on 2023-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_user_rrhh'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_rrhh',
            name='user_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
