# Generated by Django 4.1 on 2023-04-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_user_rrhh_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_rrhh',
            name='password',
            field=models.TextField(max_length=500),
        ),
    ]
