# Generated by Django 4.1 on 2023-04-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_user_rrhh_password'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user_rrhh',
            constraint=models.UniqueConstraint(fields=('user_name',), name='IntegrityError'),
        ),
    ]
