# Generated by Django 4.1 on 2023-04-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_user_rrhh_integrityerror'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user_rrhh',
            name='IntegrityError',
        ),
        migrations.AddConstraint(
            model_name='user_rrhh',
            constraint=models.UniqueConstraint(fields=('user_name',), name='mi_constraint'),
        ),
    ]
