# Generated by Django 4.1 on 2023-04-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_usuariocomun'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocomun',
            name='a_materno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usuariocomun',
            name='a_paterno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usuariocomun',
            name='nombre',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
