# Generated by Django 4.1 on 2023-04-14 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0025_usuariocomun_item_usuariocomun_reparticion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='usuarios_administradores_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarioadministrador_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.usuario')),
                ('reparticion', models.CharField(max_length=8, unique=True)),
                ('item', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('tasks.usuario',),
        ),
        migrations.CreateModel(
            name='RRHH',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.usuario')),
                ('item', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('tasks.usuario',),
        ),
        migrations.DeleteModel(
            name='UsuarioAdministrador',
        ),
        migrations.DeleteModel(
            name='UsuarioComun',
        ),
    ]
