# Generated by Django 4.1 on 2023-04-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_delete_user_rrhh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='data_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='official_permit_for_hours',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personal_leave_with_pay',
            name='user',
        ),
        migrations.RemoveField(
            model_name='register_assistence',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vacation_account_request',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vacation_rescheduling',
            name='user',
        ),
    ]
