# Generated by Django 4.1 on 2023-04-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0029_remove_commission_user_remove_data_user_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioadministrador',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuarioadministrador_permissions', to='auth.permission', verbose_name='userAdmin permissions'),
        ),
    ]
