# Generated by Django 4.1 on 2023-04-20 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0031_alter_usuarioadministrador_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioadministrador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuariocomun',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usuarioadministrador',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='usuariocomun',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='username',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='username',
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usuarioadministrador',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariocomun',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
